version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rentapark"
    ports:
      - "5433:5433"
  redis:
    container_name: "redis"
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  eureka:
    container_name: "eureka_server"
    image: "ghcr.io/code-of-us/eureka-server:latest"
    ports:
      - "8761:8761"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"