version: "3.9"

services:
  rent-a-park:
    image: 'ghcr.io/code-of-us/rent-a-park' # set the image you want to run
    build:
      context: ..
    container_name: rent-a-park
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/rentapark
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - REDIS_HOST=redis
    ports:
      - "8080:8080"