# This workflow will build a Docker image and push it to Github Container Registry

name: Publish docker image to GHCP

on:
  release:
    types: [published]
  workflow_dispatch:
env:
  VERSION_FILE: build.gradle
  VERSION_EXTRACT_PATTERN: version\s*=\s*"([^"]+)"

jobs:
  push_to_registries:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Generate versions
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}

      - name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/code-of-us/rent-a-park
          tags: ${{ env.RELEASE_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}